/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_2_tbd2;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Replicar = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        jToggleButton11 = new javax.swing.JToggleButton();
        jToggleButton12 = new javax.swing.JToggleButton();
        jToggleButton13 = new javax.swing.JToggleButton();
        jToggleButton14 = new javax.swing.JToggleButton();
        jToggleButton15 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        contraDestino = new javax.swing.JTextField();
        portDestino = new javax.swing.JTextField();
        userDestino = new javax.swing.JTextField();
        instanciaDestino = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        nombreDestino = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        contraOrigen = new javax.swing.JTextField();
        portOrigen = new javax.swing.JTextField();
        userOrigen = new javax.swing.JTextField();
        instanciaOrigen = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        nombreOrigen = new javax.swing.JTextField();
        probarDestino = new javax.swing.JToggleButton();
        probarOrigen = new javax.swing.JToggleButton();
        activoDestino = new javax.swing.JPanel();
        activoOrigen = new javax.swing.JPanel();

        jPanel4.setBackground(new java.awt.Color(153, 255, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tablas BD Origen");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 220, 40));

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 190, 240));

        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        jScrollPane6.setViewportView(jTable6);

        jPanel4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 190, 240));

        jToggleButton11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jToggleButton11.setText("<<");
        jPanel4.add(jToggleButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 70, 40));

        jToggleButton12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jToggleButton12.setText(">>");
        jPanel4.add(jToggleButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 70, 40));

        jToggleButton13.setText("Guardar");
        jPanel4.add(jToggleButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 100, 40));

        jToggleButton14.setText("Cancelar");
        jPanel4.add(jToggleButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 100, 40));

        jToggleButton15.setText("jToggleButton15");
        jToggleButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton15ActionPerformed(evt);
            }
        });
        jPanel4.add(jToggleButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 360, -1, -1));

        javax.swing.GroupLayout ReplicarLayout = new javax.swing.GroupLayout(Replicar.getContentPane());
        Replicar.getContentPane().setLayout(ReplicarLayout);
        ReplicarLayout.setHorizontalGroup(
            ReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReplicarLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        ReplicarLayout.setVerticalGroup(
            ReplicarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReplicarLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Base de Datos Origen");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 30));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Base de Datos Destino");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 190, 30));

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Puerto");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 190, 30));

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Nombre Base de Datos");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 190, 30));

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setText("Usuario");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 190, 30));

        jLabel16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("Contraseña");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 190, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Nombre Instancia");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 190, 30));

        contraDestino.setText("cosocoso");
        jPanel1.add(contraDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 180, 30));

        portDestino.setText("1433");
        jPanel1.add(portDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 180, 30));

        userDestino.setText("Admin");
        jPanel1.add(userDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 390, 180, 30));

        instanciaDestino.setText("sqlserverdb.cklxozkkkbrk.us-east-1.rds.amazonaws.com");
        jPanel1.add(instanciaDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 180, 30));

        jTextField5.setText("jTextField1");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 180, 30));

        nombreDestino.setText("Prueba");
        jPanel1.add(nombreDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 180, 30));

        jLabel18.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Puerto");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 190, 30));

        jLabel19.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Nombre Base de Datos");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 190, 30));

        jLabel20.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Usuario");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 190, 30));

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Contraseña");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 190, 30));

        jLabel22.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Nombre Instancia");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 190, 30));

        contraOrigen.setText("cosocoso");
        jPanel1.add(contraOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 180, 30));

        portOrigen.setText("3306");
        jPanel1.add(portOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 180, 30));

        userOrigen.setText("admin");
        jPanel1.add(userOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 180, 30));

        instanciaOrigen.setText("mariadb.cklxozkkkbrk.us-east-1.rds.amazonaws.com");
        jPanel1.add(instanciaOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 180, 30));

        jTextField11.setText("jTextField1");
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 180, 30));

        nombreOrigen.setText("Prueba");
        nombreOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreOrigenActionPerformed(evt);
            }
        });
        jPanel1.add(nombreOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 180, 30));

        probarDestino.setText("Probar");
        probarDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probarDestinoActionPerformed(evt);
            }
        });
        jPanel1.add(probarDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 110, 30));

        probarOrigen.setText("Probar");
        probarOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                probarOrigenActionPerformed(evt);
            }
        });
        jPanel1.add(probarOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 110, 30));

        activoDestino.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout activoDestinoLayout = new javax.swing.GroupLayout(activoDestino);
        activoDestino.setLayout(activoDestinoLayout);
        activoDestinoLayout.setHorizontalGroup(
            activoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        activoDestinoLayout.setVerticalGroup(
            activoDestinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(activoDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 470, 50, 30));

        activoOrigen.setBackground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout activoOrigenLayout = new javax.swing.GroupLayout(activoOrigen);
        activoOrigen.setLayout(activoOrigenLayout);
        activoOrigenLayout.setHorizontalGroup(
            activoOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        activoOrigenLayout.setVerticalGroup(
            activoOrigenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel1.add(activoOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreOrigenActionPerformed

    private void probarOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probarOrigenActionPerformed
        try {
            String instancia = instanciaOrigen.getText();
            String db = nombreOrigen.getText();
            String port = portOrigen.getText();
            String user = userOrigen.getText();
            String contra = contraOrigen.getText();
            MariaCon = new MariaDBCon(instancia, db, port, user, contra);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            activoOrigen.setBackground(Color.green);
            if (activoDestino.getBackground() == Color.green) {
                JOptionPane.showMessageDialog(this, "Bases de Datos Conectados");
                Replicar.pack();
                Replicar.setLocationRelativeTo(this);
                Replicar.setModal(true);
                Replicar.setVisible(true);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_probarOrigenActionPerformed

    private void probarDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_probarDestinoActionPerformed
        try {
            String instancia = instanciaDestino.getText();
            String db = nombreDestino.getText();
            String port = portDestino.getText();
            String user = userDestino.getText();
            String contra = contraDestino.getText();
            SQLCon = new SQLServerCon(instancia, db, port, user, contra);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            activoDestino.setBackground(Color.green);
            if (activoOrigen.getBackground() == Color.green) {
                JOptionPane.showMessageDialog(this, "Bases de Datos Conectados");
                Replicar.pack();
                Replicar.setLocationRelativeTo(this);
                Replicar.setModal(true);
                Replicar.setVisible(true);
                setVisible(false);
            }
        }
    }//GEN-LAST:event_probarDestinoActionPerformed

    private void jToggleButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton15ActionPerformed
        MariaCon.CrearTrigger("teachers");
    }//GEN-LAST:event_jToggleButton15ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
    SQLServerCon SQLCon;
    MariaDBCon MariaCon;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Replicar;
    private javax.swing.JPanel activoDestino;
    private javax.swing.JPanel activoOrigen;
    private javax.swing.JTextField contraDestino;
    private javax.swing.JTextField contraOrigen;
    private javax.swing.JTextField instanciaDestino;
    private javax.swing.JTextField instanciaOrigen;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTable jTable6;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton10;
    private javax.swing.JToggleButton jToggleButton11;
    private javax.swing.JToggleButton jToggleButton12;
    private javax.swing.JToggleButton jToggleButton13;
    private javax.swing.JToggleButton jToggleButton14;
    private javax.swing.JToggleButton jToggleButton15;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToggleButton jToggleButton9;
    private javax.swing.JTextField nombreDestino;
    private javax.swing.JTextField nombreOrigen;
    private javax.swing.JTextField portDestino;
    private javax.swing.JTextField portOrigen;
    private javax.swing.JToggleButton probarDestino;
    private javax.swing.JToggleButton probarOrigen;
    private javax.swing.JTextField userDestino;
    private javax.swing.JTextField userOrigen;
    // End of variables declaration//GEN-END:variables
}
